// This file has been automatically generated by writeGitVersionHeader.sh
// $Id$
#ifndef HOPSANCOREGITVERSION_H_INCLUDED
#define HOPSANCOREGITVERSION_H_INCLUDED
#define HOPSANCORE_COMMIT_HASH 8c6a04ca5
#define HOPSANCORE_COMMIT_TIMESTAMP 20210510.1904
#endif
